<StatScreen3>:
    FloatLayout:
        Button:
            pos_hint: {"top": 1, "left": 0.5}
            size_hint: 0.12,0.12
            #Credit: https://www.flaticon.com/authors/xnimrodx
            background_normal: "icons/home.png"
            on_release:
                app.change_screen("home_screen","previous")
        Button:
            pos_hint: {"top": 1, "right": 1}
            size_hint: 0.12,0.12
            text: "Submit"

